on: [push]
jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: Dependency Check Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download OWASP Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.2.1/dependency-check-8.2.1-release.zip
          unzip dependency-check-8.2.1-release.zip
          ls -la
          pwd

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          java-package: 'jdk'
          distribution: 'adopt'
          architecture: 'x64'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: 'success'
      
      - name: run commands
        run: |
            ls
            pwd
            ls -la
      - name: Run Dependency-Check
        run: |
          cd dependency-check/bin
          bash dependency-check.sh --scan . --format HTML --out reports --failOnCVSS 7 --enableRetired

       

      - name: Upload Test results
        uses: actions/upload-artifact@v2
        with:
          name: Dependency-Check Report
          path: reports
