on: [push]

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: Dependency Check Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          java-package: 'jdk'
          distribution: 'adopt'
          architecture: 'x64'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: 'success'
      
      - name: Download OWASP Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.2.1/dependency-check-8.2.1-release.zip
          unzip dependency-check-8.2.1-release.zip
          ls -la
          pwd
          cd 

      - name: Copy Project Directory
        run: |
          cp -r /home/runner/work/cybernews_test_dependency/cybernews_test_dependency /tmp/cybernews_test_dependency
          rm -rf /tmp/cybernews_test_dependency/dependency-check
          rm -f /tmp/cybernews_test_dependency/dependency-check-8.2.1-release.zip

      
      - name: Run Dependency-Check
        run: |
          cd dependency-check/bin
          bash dependency-check.sh --scan /tmp/cybernews_test_dependency --format HTML --out reports --enableRetired --enableExperimental --project "property.analyzer.python.enabled=true" --exclude "**/dependency-check,**/dependency-check-8.2.1-release.zip"

      - name: List files in reports directory
        run: |
          ls -la dependency-check/bin/reports

      - name: Upload Test results
        uses: actions/upload-artifact@v2
        with:
          name: Dependency-Check Report
          path: dependency-check/bin/reports
